import { EventPreset, EventType, MemeItem, ThemeColors, VibeType } from '@/types/ecard';

export const EVENT_MASCOTS: Record<string, string> = {
  boyfriend: '/assets/cat.gif',
  girlfriend: '/assets/boka.gif',
  bestfriend: '/assets/friend.gif',
  valentines: '/assets/love.gif',
  missyou: '/assets/missyou.gif',
  anniversary: '/assets/anniversary.gif',
  birthday: '/assets/birthday.gif',
  custom: '/assets/love.gif',
};

export function getEventMascot(evKey?: string): string {
  if (!evKey) return '/assets/cat.gif';
  return EVENT_MASCOTS[evKey] || '/assets/cat.gif';
}

export const COUPLE_GIF_ASSETS: string[] = [
  ...Array.from({ length: 20 }, (_, i) => `/assets/mini${i + 1}.gif`),
  '/assets/cat.gif',
  '/assets/boka.gif',
  '/assets/friend.gif',
  '/assets/love.gif',
  '/assets/missyou.gif',
  '/assets/birthday.gif',
  '/assets/anniversary.gif',
];

export const DEFAULT_PHOTOS = [
  '/assets/mini1.gif',
  '/assets/mini2.gif',
  '/assets/mini3.gif',
];

/* ==========================================================
   VIBE THEME PALETTES (Curated, Rich & Non-Generic)
========================================================== */
export const VIBE_THEMES: Record<VibeType, ThemeColors> = {
  romantic: {
    '--bg': '#fff0f3',
    '--ink': '#4a1525',
    '--teal': '#d85a7f',
    '--teal-d': '#a83256',
    '--mint': '#ffd6e0',
    '--peach': '#ff758f',
    '--gold': '#f3a683',
    '--line': '#fedfe6',
  },
  playful: {
    '--bg': '#fefaf0',
    '--ink': '#283618',
    '--teal': '#2a9d8f',
    '--teal-d': '#1d7066',
    '--mint': '#d8f3dc',
    '--peach': '#e76f51',
    '--gold': '#f4a261',
    '--line': '#faedcd',
  },
  nostalgic: {
    '--bg': '#f3f1f8',
    '--ink': '#241c38',
    '--teal': '#6c5ce7',
    '--teal-d': '#4834d4',
    '--mint': '#dcd6f7',
    '--peach': '#a29bfe',
    '--gold': '#fdcb6e',
    '--line': '#e2dcf7',
  },
  wholesome: {
    '--bg': '#eaf4f0',
    '--ink': '#1f3a44',
    '--teal': '#3f9482',
    '--teal-d': '#2b6f60',
    '--mint': '#cfe6df',
    '--peach': '#e07a5f',
    '--gold': '#e8a44e',
    '--line': '#cfe3dc',
  },
  funny: {
    '--bg': '#fffbf0',
    '--ink': '#3d2607',
    '--teal': '#d97706',
    '--teal-d': '#b45309',
    '--mint': '#fde68a',
    '--peach': '#f59e0b',
    '--gold': '#ea580c',
    '--line': '#fef3c7',
  },
};

/* ==========================================================
   VIBE & EVENT CONTENT ADAPTATION MATRIX (Authentic Human Tone)
========================================================== */
export interface VibeContentOverride {
  message: string;
  secretLock: {
    question: string;
    answer: string;
    hint: string;
  };
  scratchCoupons: string[];
  certTitle: string;
  terms: string[];
  memories: string[];
  voicePrompt: string;
}

export const VIBE_CONTENT_MAP: Record<EventType, Record<VibeType, VibeContentOverride>> = {
  boyfriend: {
    romantic: {
      message: "Every single day with you feels like home. Out of all 8 billion people on this planet, my heart found you, and I wouldn't change a single moment. I built this tiny corner of the internet just to remind you how deeply and truly you are loved.",
      secretLock: {
        question: "Where did we first look into each other's eyes and just knew?",
        answer: "Our first date",
        hint: "That cozy chilly evening...",
      },
      scratchCoupons: [
        "🎟️ 1x Head Massage & Unlimited Warm Cuddles",
        "🎟️ 1x Midnight Drive to Get Ice Cream Together",
        "🎟️ 1x Free Pass to Pick Any Movie (I won't fall asleep!)",
      ],
      certTitle: "Certified Supreme Boyfriend",
      terms: [
        "Forehead Kisses Policy. Guaranteed warm kisses whenever you're stressed or quiet.",
        "Safe Haven Clause. You can be fully vulnerable, silly, or tired. I've got your back.",
        "Snack Sharing Pact. What's mine is yours (especially the crispy fries).",
        "Always My Priority. Even on busy days, you're the first and last thought in my mind.",
        "Terms: valid for a lifetime, non-negotiable and unconditionally loved.",
      ],
      memories: [
        "the day you became my favourite notification ✿",
        "this smile is still my biggest weakness.",
        "we were laughing until our stomachs hurt.",
        "you make ordinary days feel magical.",
        "i'd choose you again in every single lifetime.",
        "to be continued... together forever ✿",
      ],
      voicePrompt: "Record a tender voice note telling him what he means to you...",
    },
    playful: {
      message: "Happy Boyfriend's Day to the chief instigator of all my bad decisions! You are 50% sweetheart, 50% chaotic energy, and 100% my favorite human. Here is a little corner of the internet dedicated to your goofy self.",
      secretLock: {
        question: "What's that one hilarious inside joke only we understand?",
        answer: "Fries",
        hint: "Remember that fast-food disaster...",
      },
      scratchCoupons: [
        "🎟️ 1x Get Out of 1 Silly Argument Completely Free",
        "🎟️ 1x You Pick the Takeout Dinner (No Vetoes)",
        "🎟️ 1x Free 20-Minute Back Rub on Demand",
      ],
      certTitle: "Certified Partner in Chaos",
      terms: [
        "Chief Banter Officer. Bound by contract to roast me daily, but defend me fiercely against anyone else.",
        "Fries Tax Exemption. Must hand over the best crispy fries without making a scene.",
        "Laugh at Bad Puns. Mandatory giggle even when my jokes make no sense.",
        "Spider Dispatch Duty. Officially responsible for eliminating creepy crawlies.",
        "Terms: non-refundable, non-exchangeable, stuck with me forever.",
      ],
      memories: [
        "the moment we realized we share the same broken humor.",
        "looking cute while plotting our next bad idea.",
        "proof that you can't behave for more than 5 minutes.",
        "you make boring grocery runs feel like adventures.",
        "my favorite weirdo in the entire universe.",
        "never change, silly boy ✿",
      ],
      voicePrompt: "Record a playful or teasing voice note for him...",
    },
    nostalgic: {
      message: "Looking back at old photos of us always stops me in my tracks. We've built so many sweet memories, quiet late-night talks, and unspoken understandings. Thank you for being my constant in this fast-spinning world.",
      secretLock: {
        question: "What song was playing in the background during our first drive together?",
        answer: "Until I Found You",
        hint: "Think about the soft melody we replayed...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-creating Our Very First Date Step by Step",
        "🎟️ 1x Late Night Stargazing & Unfiltered 3 AM Talks",
        "🎟️ 1x Nostalgic Photo Album Night with Warm Tea",
      ],
      certTitle: "Certified Keeper of My Heart",
      terms: [
        "Cherished Memories Treaty. We promise to never take our sweet quiet moments for granted.",
        "Late Night Listening. Always available when the world gets loud and heavy.",
        "Growing Together Pact. Supporting each other's wildest dreams and quietest fears.",
        "Timeless Connection. Proof that true love only deepens with every passing season.",
        "Terms: etched in our story, valid through all of time.",
      ],
      memories: [
        "where it all began... who knew this was the start of us?",
        "that quiet evening when everything felt peaceful.",
        "you holding my hand like you'd never let go.",
        "every milestone we conquered hand in hand.",
        "the memories that keep my heart warm on hard days.",
        "cheers to all the chapters yet to be written ✿",
      ],
      voicePrompt: "Record a nostalgic voice memo reminiscing your favorite memory together...",
    },
    wholesome: {
      message: "You bring so much gentleness, warmth, and peace into my life. Just knowing you exist in my world makes everything feel lighter and safer. I made this cozy page to send a giant warm embrace to your screen.",
      secretLock: {
        question: "What's our comfort food when we've had a long exhausting day?",
        answer: "Pizza",
        hint: "Warm, cheesy, and best eaten in sweatpants...",
      },
      scratchCoupons: [
        "🎟️ 1x Blanket Burrito + Hot Beverage + Zero Chores",
        "🎟️ 1x Unlimited Cozy Cuddles with Soft Music",
        "🎟️ 1x Home-Cooked Favorite Meal Made by Me",
      ],
      certTitle: "Certified Most Wholesome Human",
      terms: [
        "Comfort Priority. You are always allowed to rest, recharge, and be soft.",
        "Unconditional Hype Person. I will forever be your biggest fan and quietest comfort.",
        "Safe Space Guarantee. No judgment, no pretense, just pure warmth.",
        "Hydration & Snack Reminder. Bound to be gently reminded to drink water and take care.",
        "Terms: blessed with pure comfort and endless care.",
      ],
      memories: [
        "the sweetest smile that brightens any rainy day.",
        "pure, quiet comfort in human form.",
        "just us being soft and peaceful together.",
        "thank you for always being my safe place.",
        "you make the world a gentler place to live in.",
        "sending you all the love in the universe ✿",
      ],
      voicePrompt: "Record a warm, comforting voice note for him...",
    },
    funny: {
      message: "Look at you, being an absolute legend and putting up with my nonsense 365 days a year! You deserve a national holiday, but since the government won't pass the bill, I made you this website instead. You're welcome.",
      secretLock: {
        question: "Who takes longer to get ready and who denies it?",
        answer: "Both of us",
        hint: "We both know the truth...",
      },
      scratchCoupons: [
        "🎟️ 1x 24 Hours of Me Admitting You Were Right (Once!)",
        "🎟️ 1x I Won't Steal Any of Your Food Today",
        "🎟️ 1x Free Pass to Play Games All Evening Uninterrupted",
      ],
      certTitle: "Certified Survivor of My Antics",
      terms: [
        "Patience Medal of Honor. For enduring my mood swings and dramatic reenactments.",
        "Aux Cord Authority. Granted 50% music control, provided you don't skip my bangers.",
        "Photo Shoot Endurance. Required to take at least 15 photos until we get 'the one'.",
        "Snack Security Breach. Accepted that my hands will enter your snack bag without warning.",
        "Terms: lifetime sentence, no possibility of parole.",
      ],
      memories: [
        "the face you make when I ask for a bite of your food.",
        "we look surprisingly civilized here.",
        "a rare photographic evidence of you behaving.",
        "partners in crime and embarrassing moments.",
        "I love you even when you chew like a tractor.",
        "stay unhinged, my favorite weirdo ✿",
      ],
      voicePrompt: "Record a funny roast or dramatic voice message...",
    },
  },

  girlfriend: {
    romantic: {
      message: "From the moment you walked into my life, everything turned softer, brighter, and infinitely more beautiful. You deserve all the princess treatment in the world, starting with this little digital garden grown just for you.",
      secretLock: {
        question: "What is the single thing that makes my heart skip every time you do it?",
        answer: "Your laugh",
        hint: "The cutest sound in the entire world...",
      },
      scratchCoupons: [
        "🎟️ 1x Full Royal Princess Treatment Day (Zero Stress)",
        "🎟️ 1x Late Night Boba & Sweet Treat Run on My Tab",
        "🎟️ 1x 100 Forehead Kisses & Long Cozy Hugs",
      ],
      certTitle: "World's Best Girlfriend & Queen of My Heart",
      terms: [
        "Lifetime Princess Treatment. Guaranteed flowers, forehead kisses, and undivided attention.",
        "Always Right Treaty. In any minor dispute, Rule #1 applies: She is always right.",
        "Warm Hugs on Demand. Mandatory soft snuggles whenever you feel chilly or overwhelmed.",
        "Boba & Dessert Immunity. Free to take the best sip or bite without objection.",
        "Terms: loved endlessly, today, tomorrow, and forever.",
      ],
      memories: [
        "the moment you smiled and my heart knew it was home.",
        "my absolute favorite place in the world is right beside you.",
        "you make the entire universe softer and prettier.",
        "every little photo of you is my treasured masterpiece.",
        "falling in love with you was the easiest thing I ever did.",
        "forever your biggest fan and protector ✿",
      ],
      voicePrompt: "Leave a romantic voice note telling her she's your whole world...",
    },
    playful: {
      message: "Happy Girlfriend's Day to the prettiest menace in town! You steal my hoodies, you steal my food, and you stole my heart. I wouldn't have it any other way. Here is your official shrine on the internet!",
      secretLock: {
        question: "How many of my hoodies do you currently have in your closet?",
        answer: "All of them",
        hint: "They look better on you anyway...",
      },
      scratchCoupons: [
        "🎟️ 1x Steal Any Hoodie From My Closet Permanently",
        "🎟️ 1x I Watch Your Favorite Rom-Com Without Complaining",
        "🎟️ 1x Emergency Bubble Tea Delivery When Cranky",
      ],
      certTitle: "Certified Queen of Sassy Cuties",
      terms: [
        "Hoodie Confiscation Rights. Legally entitled to wear any oversized jacket of mine.",
        "Indecisive Food Pass. Allowed 45 minutes to answer 'what do you want to eat?'.",
        "Cute Rage Immunity. Being hangry or pouty shall be met with snacks and hugs.",
        "Personal Paparazzo. I am obligated to take aesthetic photos of you from all angles.",
        "Terms: stuck with me for life, no exchanges or refunds.",
      ],
      memories: [
        "caught in 4k being an adorable menace.",
        "the face you make before stealing my food.",
        "you being cute and knowing you can get away with anything.",
        "partners in sassy banter since day one.",
        "I love you more than you love my oversized hoodies.",
        "forever your loyal cheerleader ✿",
      ],
      voicePrompt: "Record a funny, loving voice memo for her...",
    },
    nostalgic: {
      message: "Every little milestone we've shared feels like a fairytale I never want to wake up from. Seeing your smile through the seasons has been the greatest gift of my life. Thank you for walking this road with me.",
      secretLock: {
        question: "Where did we first hold hands under the evening lights?",
        answer: "The park",
        hint: "That quiet romantic walk...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-visiting the Place Where We Had Our First Date",
        "🎟️ 1x Candlelight Dinner with Our Favorite Soundtrack",
        "🎟️ 1x Scrapbook Night Reminiscing All Our Old Memories",
      ],
      certTitle: "Certified Love of My Lifetime",
      terms: [
        "Timeless Devotion. A promise to love you in every season and every chapter.",
        "Quiet Moments Treaty. Cherishing the slow mornings and cozy evenings together.",
        "Endless Support. Standing by your side through every triumph and every tear.",
        "Sweet Reminders. Bound to remind you how deeply treasured you are every day.",
        "Terms: written in the stars, everlasting and true.",
      ],
      memories: [
        "our first photo together... I was already so nervous and happy.",
        "that unforgettable evening when the world felt still.",
        "every candid smile of yours is etched in my mind.",
        "the way your eyes light up when you're happy.",
        "thank you for choosing me every single day.",
        "forever and always, my sweet girl ✿",
      ],
      voicePrompt: "Record a nostalgic voice memo about your favorite memory with her...",
    },
    wholesome: {
      message: "You bring so much light, comfort, and gentle warmth wherever you go. Your sweet heart deserves nothing less than pure joy, endless peace, and lots of cozy cuddles. I hope this little page puts a huge smile on your face.",
      secretLock: {
        question: "What's our favorite cozy comfort activity on a rainy day?",
        answer: "Movie and blankets",
        hint: "Hot drink + fluffy blankets + movies...",
      },
      scratchCoupons: [
        "🎟️ 1x Unlimited Head Scratches & Gentle Hair Stroking",
        "🎟️ 1x Fresh Flowers Delivered to Brighten Your Day",
        "🎟️ 1x Complete Relaxation Day with Zero Responsibilities",
      ],
      certTitle: "Certified Angel of Pure Sunshine",
      terms: [
        "Tender Care Clause. Guaranteed forehead kisses and comforting words when tired.",
        "Safe Harbor Treaty. A soft, warm hug waiting for you whenever you need it.",
        "Daily Appreciation. Acknowledging all the wonderful little things you do.",
        "Sweet Treat Protocol. Priority delivery of comfort snacks and sweet drinks.",
        "Terms: blessed with pure happiness and everlasting love.",
      ],
      memories: [
        "pure sunshine in human form.",
        "your smile makes the hardest days easy.",
        "softest and sweetest moments with you.",
        "thank you for making life feel so gentle.",
        "my favorite place will always be in your warmth.",
        "you deserve all the goodness in the world ✿",
      ],
      voicePrompt: "Record a warm, comforting voice note for her...",
    },
    funny: {
      message: "Happy Girlfriend's Day to the only person allowed to bully me with complete immunity! You are dramatic, you are hilarious, and I am utterly obsessed with you. Please accept this digital certificate of your supreme reign.",
      secretLock: {
        question: "Who is the drama queen in this relationship (and why is it you)?",
        answer: "Me",
        hint: "Admit it, it's cute...",
      },
      scratchCoupons: [
        "🎟️ 1x I Won't Complain When You Take 50 Selfies",
        "🎟️ 1x Late Night Snack Run Even If I'm Already in Bed",
        "🎟️ 1x Free Pass to Use My Arm as a Pillow Until It Goes Numb",
      ],
      certTitle: "Certified Supreme Drama Queen & Boss",
      terms: [
        "Bed Territory Rights. Entitled to 85% of the bed and all the fluffy blankets.",
        "Decision Offloading. Can say 'you decide' and then reject all 5 suggestions.",
        "Photographic Perfection. Obligated to retake the photo until your hair looks flawless.",
        "Cold Feet Warming. Allowed to place icy cold toes on my warm legs without warning.",
        "Terms: signed under duress, valid indefinitely.",
      ],
      memories: [
        "exhibit A: being dramatically adorable.",
        "the look of someone who just got their way.",
        "proof that you run this entire operation.",
        "laughing at our own stupid jokes for an hour.",
        "I love you even when you're being completely unhinged.",
        "cheers to my favorite menace ✿",
      ],
      voicePrompt: "Record a funny, teasing voice note for her...",
    },
  },

  bestfriend: {
    romantic: {
      message: "Soulmates aren't just romantic — some soulmates come in the form of best friends who know your entire soul. Thank you for being the person who knows all my secrets, holds my hand through the storm, and celebrates every win.",
      secretLock: {
        question: "What was the exact moment we knew we were best friends for life?",
        answer: "First deep talk",
        hint: "That late night talk when everything clicked...",
      },
      scratchCoupons: [
        "🎟️ 1x Deep Late Night Heart-to-Heart with Tea",
        "🎟️ 1x Weekend Trip Planned & Paid by Me",
        "🎟️ 1x Unlimited Tight Hugs & Life Support",
      ],
      certTitle: "Certified Soul Bestie & Life Companion",
      terms: [
        "Soulmate Treaty. Recognized as my irreplaceable soul best friend.",
        "Unfiltered Truth. Always offering honest advice and loving support.",
        "3 AM Lifeline. Available whenever life feels heavy.",
        "Celebrate Every Win. Guaranteed loudest cheerleader in the room.",
        "Terms: friends for this lifetime and all to follow.",
      ],
      memories: [
        "the day I found my soul best friend.",
        "laughter that heals every wound.",
        "side by side through every storm.",
        "thank you for always believing in me.",
        "you are family that I chose myself.",
        "best friends forever and always ✿",
      ],
      voicePrompt: "Record a heartfelt message for your best friend...",
    },
    playful: {
      message: "We don't say it often because we're busy roasting each other into oblivion, but you are my absolute favorite human. From chaotic 3 AM calls to terrible ideas we'd repeat in a heartbeat, you're stuck with me forever.",
      secretLock: {
        question: "What's our most unhinged shared secret?",
        answer: "That crazy trip",
        hint: "The one we swore to take to the grave...",
      },
      scratchCoupons: [
        "🎟️ 1x Free Food & Drinks on My Tab",
        "🎟️ 1x Unfiltered 2 AM Vent Session (Zero Judgment)",
        "🎟️ 1x Emergency Fake Call to Escape a Bad Date",
      ],
      certTitle: "Certified Partner in Chaos & Crime",
      terms: [
        "Chief Gossip Officer. Bound by sacred oath to listen to all 10-minute voice notes.",
        "Shared Brain Cell Policy. We agree to never judge each other's questionable life choices.",
        "Mutual Roasting Immunity. We insult each other daily, but fight anyone else who tries.",
        "Emergency Date Rescue. Must call with a fake crisis if the date is terrible.",
        "Terms: best friends forever, you know too many secrets to be released.",
      ],
      memories: [
        "remember when we thought this was a genius plan?",
        "the hardest laughs are always the ones with you.",
        "partners in crime and chaotic energy.",
        "distance means nothing when a bond is this cracked.",
        "thank you for matching my exact brand of crazy.",
        "stuck with me for life, no refunds ✿",
      ],
      voicePrompt: "Record a funny roast or chaotic voice memo for your bestie...",
    },
    nostalgic: {
      message: "Looking at old photos of our friendship makes me smile so hard. We've grown, we've changed, but the bond we share has only gotten stronger. Here's a tribute to all our milestones and memories.",
      secretLock: {
        question: "Where did we take our very first road trip or adventure together?",
        answer: "Road trip",
        hint: "Windows down, singing at the top of our lungs...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-visiting Our Old Favorite Hangout Spot",
        "🎟️ 1x Binge-Watching Our Nostalgic Childhood Shows",
        "🎟️ 1x Old School Photo Dump & Reminiscing Night",
      ],
      certTitle: "Certified Lifelong Friend & Memory Keeper",
      terms: [
        "Nostalgia Pact. We promise to never forget where we started.",
        "Through Every Season. Growing together no matter where life takes us.",
        "Unbreakable Bond. Decades of memories that time can never erase.",
        "Golden Memories. Celebrating our journey from day one to forever.",
        "Terms: certified for life, renewed automatically every year.",
      ],
      memories: [
        "baby versions of us back in the day.",
        "all the adventures that made us who we are.",
        "proof that time changes nothing between us.",
        "through every high and every low, together.",
        "grateful for every single memory with you.",
        "cheers to 50 more years of friendship ✿",
      ],
      voicePrompt: "Record a nostalgic voice memo for your best friend...",
    },
    wholesome: {
      message: "Having you in my corner is one of the biggest blessings of my life. Thank you for being the friend who genuinely listens, always shows up, and makes the world feel so much kinder.",
      secretLock: {
        question: "What's our comfort comfort hangout when we both have zero energy?",
        answer: "Couch and snacks",
        hint: "Doing absolutely nothing together in silence...",
      },
      scratchCoupons: [
        "🎟️ 1x Wholesome Spa & Self-Care Day Together",
        "🎟️ 1x Cozy Coffee & Long Walk Catch-Up Session",
        "🎟️ 1x Your Favorite Homemade Treat Delivered by Me",
      ],
      certTitle: "Certified Pure Gold Best Friend",
      terms: [
        "Kindness Guarantee. Always offering a listening ear and warm support.",
        "Zero Pressure Pact. Comfortable sitting in silence without awkwardness.",
        "Safe Haven. You can always tell me anything without fear of judgment.",
        "Mutual Affirmation. Constantly reminding you how incredible you are.",
        "Terms: blessed with pure kindness and lifelong loyalty.",
      ],
      memories: [
        "the purest friendship in the world.",
        "always bringing sunshine into my life.",
        "gentle moments of genuine connection.",
        "thank you for always having my back.",
        "a friend that feels like family.",
        "so lucky to have you in my corner ✿",
      ],
      voicePrompt: "Record a sweet, supportive voice note for your best friend...",
    },
    funny: {
      message: "If we get arrested together, I am immediately blaming you. But honestly, there is nobody else I'd rather share a jail cell with. Happy Friendship Day to my favorite menace to society!",
      secretLock: {
        question: "Who makes worse decisions and who eagerly agrees to join?",
        answer: "We both do",
        hint: "Zero hesitation every time...",
      },
      scratchCoupons: [
        "🎟️ 1x I Pay for the Uber When You're Too Lazy",
        "🎟️ 1x You Can Complain About the Same Thing 10 Times",
        "🎟️ 1x I Won't Tell Anyone That Embarrassing Story (Today)",
      ],
      certTitle: "Certified Accomplice in Public Embarrassment",
      terms: [
        "Alibi Provider. Bound by friendship law to confirm any fake excuse.",
        "Screenshot Vault. Guarding 10,000 incriminating screenshots with your life.",
        "Brain Cell Custody. Rotating the single shared brain cell on alternate days.",
        "Roast Protocol. Required to humble me when my ego gets too high.",
        "Terms: you know too much, there is no escape.",
      ],
      memories: [
        "the exact face of a chaotic mastermind.",
        "nobody else understands why this was funny.",
        "two clowns in their natural habitat.",
        "we really thought we were doing something here.",
        "never let us out in public unsupervised again.",
        "stuck with me forever, bestie ✿",
      ],
      voicePrompt: "Record a funny roast or voice note for your bestie...",
    },
  },

  valentines: {
    romantic: {
      message: "Out of all the people and places in this vast world, my favorite place will always be right beside you. Thank you for filling every single day with butterflies, warmth, and sweet memories. Happy Valentine's Day, my forever love.",
      secretLock: {
        question: "What is our song that makes everything else disappear?",
        answer: "Perfect",
        hint: "Our romantic soundtrack...",
      },
      scratchCoupons: [
        "🎟️ 1x Romantic Candlelight Dinner & Slow Dance at Home",
        "🎟️ 1x 100 Kisses Redeemable Anywhere, Anytime",
        "🎟️ 1x Dream Weekend Getaway Planned Completely by Me",
      ],
      certTitle: "Certified Supreme Valentine & Eternal Soulmate",
      terms: [
        "Endless Love Treaty. Loving you deeper with every beat of my heart.",
        "Priority Cuddle Access. Non-negotiable access to warm embraces.",
        "Forever Valentine. Automatically renewed for this lifetime and the next.",
        "Sweet Romance Protocol. Surprise dates, flowers, and gentle kisses.",
        "Terms: sealed with love, forever and always.",
      ],
      memories: [
        "you are my favorite thought every single morning.",
        "out of everyone in the world, it will always be you.",
        "the quiet moments with you mean everything to me.",
        "you feel like home in human form.",
        "i love you more than words could ever express.",
        "happy valentine's day, my forever love ✿",
      ],
      voicePrompt: "Record a deeply romantic Valentine's voice message...",
    },
    playful: {
      message: "Happy Valentine's Day to my favorite distraction! You stole my heart, but I'll let it slide because you're cute. Let's eat way too much chocolate and be silly together.",
      secretLock: {
        question: "Who fell in love first vs who fell harder?",
        answer: "Both of us",
        hint: "The sweetest tie...",
      },
      scratchCoupons: [
        "🎟️ 1x You Pick What We Eat Without 40 Minutes of Debating",
        "🎟️ 1x Unlimited Chocolate & Dessert on My Tab",
        "🎟️ 1x 100 Cheesy Pick-Up Lines Delivered in Person",
      ],
      certTitle: "Certified Valentine & Cutie of the Year",
      terms: [
        "Chocolate Tax Exemption. You get first pick of all Valentine's sweets.",
        "Cuddle Monopoly. Mandatory snuggles during movie marathons.",
        "Cheesy Love Pass. Allowed to send cringe romantic memes without judgment.",
        "Heart Thief Immunity. Officially pardoned for stealing my heart.",
        "Terms: valid forever, non-transferable.",
      ],
      memories: [
        "happy valentine's day to my favorite human.",
        "look at us being all cute and in love.",
        "you make my heart do weird backflips.",
        "my favorite person to eat snacks with.",
        "loving you is the most fun thing in the world.",
        "forever your silly valentine ✿",
      ],
      voicePrompt: "Record a playful Valentine's voice memo...",
    },
    nostalgic: {
      message: "Every Valentine's with you reminds me how lucky I was the day our paths crossed. Thank you for building this beautiful love story with me, step by step, memory by memory.",
      secretLock: {
        question: "Where did we celebrate our very first Valentine's Day?",
        answer: "Our first dinner",
        hint: "Think back to when we were both nervous...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-creating Our First Valentine's Date",
        "🎟️ 1x Scrapbook Night with Old Photos & Wine",
        "🎟️ 1x Stargazing and Reminiscing Our Journey",
      ],
      certTitle: "Certified Timeless Valentine",
      terms: [
        "Everlasting Romance. Proof that true love grows sweeter every year.",
        "Memory Preservation. Keeping our sweetest moments alive in our hearts.",
        "Growing Together. Hand in hand through all of life's chapters.",
        "Endless Appreciation. Never taking a single day for granted.",
        "Terms: timeless, enduring, and forever true.",
      ],
      memories: [
        "our first valentine together... look how far we've come.",
        "every year with you is sweeter than the last.",
        "you are still the one I fall for every day.",
        "grateful for every chapter of our love story.",
        "my heart has always belonged to you.",
        "happy valentine's day, my timeless love ✿",
      ],
      voicePrompt: "Record a nostalgic Valentine's voice memo...",
    },
    wholesome: {
      message: "Valentine's Day is just an excuse to remind you of what I feel every single day: having your gentle, kind heart in my life is the greatest gift. Sending you the warmest hug.",
      secretLock: {
        question: "What's our favorite simple pleasure to do together?",
        answer: "Walking together",
        hint: "Holding hands in the quiet evening...",
      },
      scratchCoupons: [
        "🎟️ 1x Hand-Picked Fresh Flowers & Sweet Note",
        "🎟️ 1x Cozy Breakfast in Bed Made with Love",
        "🎟️ 1x Warmest Blanket Burrito & Cuddle Session",
      ],
      certTitle: "Certified Pure Heart Valentine",
      terms: [
        "Gentle Love Treaty. Loving you softly, kindly, and unconditionally.",
        "Peaceful Comfort. A safe harbor whenever the world feels overwhelming.",
        "Daily Sweetness. Celebrating your beautiful soul every single day.",
        "Warm Hugs Guarantee. Unlimited comforting embraces on demand.",
        "Terms: wrapped in warmth and pure love.",
      ],
      memories: [
        "pure warmth and love in human form.",
        "the sweetest soul I've ever known.",
        "thank you for making every day gentle.",
        "you make my heart feel so peaceful.",
        "blessed to love and be loved by you.",
        "happy valentine's day to my angel ✿",
      ],
      voicePrompt: "Record a sweet, heartwarming Valentine's voice message...",
    },
    funny: {
      message: "Congratulations on having the most attractive, funny, and humble Valentine on the planet! You really hit the jackpot. I love you more than pizza, which is saying a lot.",
      secretLock: {
        question: "Who is the luckier one in this relationship?",
        answer: "You are",
        hint: "We both know it's you...",
      },
      scratchCoupons: [
        "🎟️ 1x I Won't Eat Any of Your Valentine's Chocolates",
        "🎟️ 1x Free Pass to Pick the Restaurant (No Vetoes)",
        "🎟️ 1x 24 Hours of Pure Royal Princess/Prince Treatment",
      ],
      certTitle: "Certified Winner of the Valentine Lottery",
      terms: [
        "Jackpot Verification. Officially certified to have bagged a 10/10 partner.",
        "Chocolate Rights. Guaranteed 80% share of all gift baskets.",
        "Cuddle Priority. Mandatory spooning on demand.",
        "Love Overload. Must endure cheesy compliments all day.",
        "Terms: prize non-refundable and non-exchangeable.",
      ],
      memories: [
        "look at you bagging such a catch.",
        "we look ridiculously good together.",
        "happy valentine's to my favorite weirdo.",
        "I love you even when you steal my snacks.",
        "best valentine in the entire galaxy.",
        "cheers to us, superstar ✿",
      ],
      voicePrompt: "Record a funny, roasty Valentine's voice message...",
    },
  },

  missyou: {
    romantic: {
      message: "Distance may keep us from holding hands right now, but it has zero power over what we share. Every second away from you only proves how much you mean to my heart. Counting down every beat until I'm in your arms again.",
      secretLock: {
        question: "Where is the first place we are going the moment we meet?",
        answer: "Airport hug",
        hint: "Where our longest reunion embrace happens...",
      },
      scratchCoupons: [
        "🎟️ 1x Non-Stop 10-Minute Tight Reunion Hug",
        "🎟️ 1x Sleep on FaceTime Pass (No Hanging Up!)",
        "🎟️ 1x Your Favorite Home-Cooked Meal on Arrival",
      ],
      certTitle: "Certified Most Deeply Missed Person",
      terms: [
        "Distance-Proof Heart. Physical miles have zero strength against our connection.",
        "Nightly Goodnight Protocol. Daily night texts and voice notes are non-negotiable.",
        "Reunion Treaty. Minimum 10-minute tight hug upon seeing each other.",
        "Virtual Hug Dispensary. Unlimited virtual embraces whenever days feel long.",
        "Terms: countdown active until there is zero distance between us.",
      ],
      memories: [
        "missing you a little extra today and every single day.",
        "looking at pictures of us until I get to hold your hand again.",
        "every mile between us is so worth it for you.",
        "can't wait for our next sweetest reunion hug.",
        "my heart is right wherever you are.",
        "see you soon, my favorite human ✿",
      ],
      voicePrompt: "Record your voice for when they miss you at 2 AM...",
    },
    playful: {
      message: "Excuse me, you are too far away and it is entirely unacceptable. Who is going to steal my fries and annoy me in person? Hurry up and get back so we can resume our chaotic adventures!",
      secretLock: {
        question: "What's the first silly thing we're doing when we reunite?",
        answer: "Get food",
        hint: "Our favorite shared obsession...",
      },
      scratchCoupons: [
        "🎟️ 1x Aggressive Reunion Squeeze & Tackle Hug",
        "🎟️ 1x All the Takeout Food You Craved on My Tab",
        "🎟️ 1x 24 Hours of Me Being at Your Beck and Call",
      ],
      certTitle: "Certified Too Far Away Cutie",
      terms: [
        "Anti-Distance Treaty. Long distance is officially declared illegal.",
        "Daily Meme Quota. Mandatory sharing of at least 5 funny memes daily.",
        "FaceTime Emergency Pass. Can call at any hour just to stare at each other.",
        "Reunion Pampering. Guaranteed VIP treatment upon arrival.",
        "Terms: valid until you are physically back in my arms.",
      ],
      memories: [
        "proof that you need to be closer immediately.",
        "missing my favorite partner in crime.",
        "looking at this picture instead of doing work.",
        "can we skip to the part where we're together?",
        "you're stuck with my 20-minute voice notes.",
        "see you soon, you big cutie ✿",
      ],
      voicePrompt: "Record a playful voice note about how much you miss them...",
    },
    nostalgic: {
      message: "Looking at photos from when we were together makes the distance feel a little softer. The miles between us are temporary, but the love we've built is permanent. Counting down every single day.",
      secretLock: {
        question: "What song makes us feel close even when we're miles apart?",
        answer: "Our melody",
        hint: "The track on our shared playlist...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-living Our Favorite Day Together Step by Step",
        "🎟️ 1x Virtual Movie Night with Matching Snacks",
        "🎟️ 1x Countdown Calendar to Our Next Adventure",
      ],
      certTitle: "Certified Miles & Memories Champion",
      terms: [
        "Under the Same Sky. Remembering that the same moon shines on both of us.",
        "Memory Anchor. Holding onto our sweetest moments when lonely.",
        "Unwavering Loyalty. Growing stronger through the miles.",
        "Future Reunion Pact. Building toward our forever together.",
        "Terms: distance means nothing when someone means everything.",
      ],
      memories: [
        "the memory that keeps my heart warm every night.",
        "standing under the same sky, thinking of you.",
        "every second apart brings us one second closer.",
        "the warmth of your hand still lingers in mine.",
        "distance is just a test of how far love can travel.",
        "always yours, no matter the miles ✿",
      ],
      voicePrompt: "Record a tender voice memo for the long distance...",
    },
    wholesome: {
      message: "Sending you the biggest, warmest digital hug across the miles. Even when we're apart, your presence brings so much peace to my heart. Take good care of yourself until I can hug you in person.",
      secretLock: {
        question: "What's our favorite goodnight routine over the phone?",
        answer: "Sleep call",
        hint: "Whispering goodnight until we fall asleep...",
      },
      scratchCoupons: [
        "🎟️ 1x Unlimited Virtual Warm Hugs & Comfort Notes",
        "🎟️ 1x Care Package Filled with Your Favorite Goodies",
        "🎟️ 1x Peaceful Sleep Call with Soft Lofi Music",
      ],
      certTitle: "Certified Connected at Heart",
      terms: [
        "Gentle Distance Treaty. Always reminding each other that love knows no distance.",
        "Self-Care Reminder. Bound to eat well and sleep softly.",
        "Open Line of Comfort. Available whenever distance feels heavy.",
        "Warm Embrace Guarantee. A real hug waiting for you at the finish line.",
        "Terms: holding you tight in my heart always.",
      ],
      memories: [
        "miles apart, but forever close at heart.",
        "sending warmth across every mile.",
        "my favorite human in the entire world.",
        "counting the days until our sweet reunion.",
        "you are always in my thoughts and prayers.",
        "stay safe and warm, my love ✿",
      ],
      voicePrompt: "Record a gentle, comforting voice memo for them...",
    },
    funny: {
      message: "I miss you like a phone with 1% battery misses a charger. Please stop being in a different location code and report back to my vicinity immediately. Thank you for your cooperation.",
      secretLock: {
        question: "What's the #1 thing you're going to steal from me when we meet?",
        answer: "Food and hoodies",
        hint: "You never change...",
      },
      scratchCoupons: [
        "🎟️ 1x Free Pass to Complain About How Far Away We Are",
        "🎟️ 1x I Promise Not to Fall Asleep on FaceTime (Once)",
        "🎟️ 1x All Your Favorite Foods Delivered to Your Door",
      ],
      certTitle: "Certified Distance Violation Offender",
      terms: [
        "Immediate Relocation Request. Strongly encouraged to teleport back.",
        "FaceTime Mandate. Must show face and not just the ceiling fan.",
        "Voice Note Listening. Obligated to listen to all my chaotic updates.",
        "Reunion Tax. Owed 100 hugs and unlimited snacks upon arrival.",
        "Terms: non-negotiable, miss you too much.",
      ],
      memories: [
        "why are you all the way over there?",
        "missing your goofy face in person.",
        "me looking at your location like 👁️👄👁️",
        "who is going to laugh at my bad jokes now?",
        "hurry back, I'm tired of hugging my pillow.",
        "come back soon, weirdo ✿",
      ],
      voicePrompt: "Record a funny, dramatic voice note about the distance...",
    },
  },

  anniversary: {
    romantic: {
      message: "Another year has passed, and loving you only gets sweeter, deeper, and more magical. Looking back at everything we've built, I'd choose you all over again in every single lifetime. Happy Anniversary, my entire world.",
      secretLock: {
        question: "The exact moment when we decided our forever began?",
        answer: "Our first anniversary",
        hint: "That starry romantic night...",
      },
      scratchCoupons: [
        "🎟️ 1x Surprise Anniversary Getaway Planned by Me",
        "🎟️ 1x Re-creating Our First Romantic Date Together",
        "🎟️ 1x Candlelight Dinner & Memory Scrapbook Night",
      ],
      certTitle: "Certified Milestone of Everlasting Love",
      terms: [
        "Still the One. Officially re-affirming that I would choose you over and over.",
        "Anniversary Pampering. Deserves special treats, good food, and slow dances.",
        "Shared Future Pact. Building our sweetest dreams together, day by day.",
        "Lifelong Partnership. In every laugh, every tear, and every victory.",
        "Terms: renewed automatically every year with 100-year warranty.",
      ],
      memories: [
        "day one with you was amazing, but today is even better.",
        "thank you for choosing me every single day.",
        "all our memories feel like a fairytale come true.",
        "cheers to another year of us being us.",
        "loving you is the greatest adventure of my life.",
        "happy anniversary to my entire world ✿",
      ],
      voicePrompt: "Record an anniversary voice message from the heart...",
    },
    playful: {
      message: "Happy Anniversary! We survived another whole year without killing each other — that definitely calls for celebration! You're still my favorite person to annoy.",
      secretLock: {
        question: "What's the funniest argument we had this year that we laugh about now?",
        answer: "Where to eat",
        hint: "The eternal question...",
      },
      scratchCoupons: [
        "🎟️ 1x Complete Immunity from Being Annoyed for 24 Hours",
        "🎟️ 1x Fancy Dinner on My Tab (Dessert Included!)",
        "🎟️ 1x You Pick the Weekend Activity (Zero Complaints)",
      ],
      certTitle: "Certified Anniversary Survival Champions",
      terms: [
        "Another Year Survived. Proving that our chaos is mutually compatible.",
        "Aux Cord Rights. Shared rights to the road trip playlist.",
        "Anniversary Feast. Obligated to eat until we can't move.",
        "Teamwork Award. For defeating every silly obstacle together.",
        "Terms: contract extended for another 100 years.",
      ],
      memories: [
        "another year of putting up with me.",
        "we clean up surprisingly well.",
        "my favorite partner in crime for another year.",
        "still crazy in love with your goofy self.",
        "cheers to more chaotic adventures together.",
        "happy anniversary, superstar ✿",
      ],
      voicePrompt: "Record a playful anniversary voice message...",
    },
    nostalgic: {
      message: "Flipping through all the photos from our journey together brings tears of happiness to my eyes. We've weathered storms, celebrated milestones, and grown so much. Happy Anniversary to my forever partner.",
      secretLock: {
        question: "Where were we when we realized this was forever?",
        answer: "By the water",
        hint: "That quiet evening under the stars...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-visiting the Place Where We First Met",
        "🎟️ 1x Photo Album Night with Warm Tea & Memories",
        "🎟️ 1x Renewing Our Promises Under the Night Sky",
      ],
      certTitle: "Certified Golden Journey of Love",
      terms: [
        "Timeless Devotion. Honoring every chapter of our shared journey.",
        "Deepening Bond. Growing stronger with every passing season.",
        "Cherished Milestones. Remembering every step that brought us here.",
        "Forever Growing. Hand in hand into the future.",
        "Terms: etched in our story, everlasting and pure.",
      ],
      memories: [
        "where it all began... so young and full of dreams.",
        "every milestone conquered side by side.",
        "all the quiet moments that meant the most.",
        "thank you for standing by me through it all.",
        "my heart is forever grateful for our journey.",
        "happy anniversary to my one and only ✿",
      ],
      voicePrompt: "Record a nostalgic anniversary voice note...",
    },
    wholesome: {
      message: "Happy Anniversary to the kindest, gentlest soul in my life. Every day spent with you brings so much peace, comfort, and gratitude to my heart. Here's to us and many more peaceful years.",
      secretLock: {
        question: "What's our favorite quiet ritual together?",
        answer: "Morning coffee",
        hint: "Soft mornings talking about life...",
      },
      scratchCoupons: [
        "🎟️ 1x Cozy Breakfast in Bed with Your Favorite Treats",
        "🎟️ 1x Relaxing Spa & Gentle Pampering Day",
        "🎟️ 1x Long Quiet Walk in Nature Holding Hands",
      ],
      certTitle: "Certified Pure Comfort Partnership",
      terms: [
        "Gentle Companionship. Supporting each other with tenderness and care.",
        "Peaceful Home. Making our shared space full of warmth and love.",
        "Daily Gratitude. Acknowledging the beauty in simple moments.",
        "Unconditional Care. Always having a safe harbor in each other.",
        "Terms: blessed with pure joy and everlasting peace.",
      ],
      memories: [
        "pure happiness in human form.",
        "another beautiful year of gentle love.",
        "so grateful for every peaceful moment with you.",
        "you make life feel so calm and safe.",
        "cheers to a lifetime of quiet joy together.",
        "happy anniversary, my sweetest angel ✿",
      ],
      voicePrompt: "Record a sweet, heartwarming anniversary message...",
    },
    funny: {
      message: "Happy Anniversary! I still love you even when you steal the covers, forget where you put your keys, and talk through the best part of the movie. Here's to us, the dynamic duo!",
      secretLock: {
        question: "Who is the boss in this relationship?",
        answer: "You know who",
        hint: "The one who decides dinner...",
      },
      scratchCoupons: [
        "🎟️ 1x I Won't Mention Your Bad Driving for 48 Hours",
        "🎟️ 1x All-You-Can-Eat Dessert Night on My Tab",
        "🎟️ 1x 100 Free Hugs When You're Being Dramatic",
      ],
      certTitle: "Certified Partners in Unhinged Romance",
      terms: [
        "Patience of a Saint. Awarded for surviving each other another 365 days.",
        "Cover Stealing Amnesty. Pardoned for hogging 90% of the blanket.",
        "Selective Hearing Rights. Granted permission to nod while zoning out.",
        "Teamwork Trophy. Winning at life and couple goals together.",
        "Terms: automatically renewed forever with no exit clause.",
      ],
      memories: [
        "another year of tolerating my nonsense.",
        "look at us surviving adulthood together.",
        "who let us get this far?",
        "my favorite person to do absolutely nothing with.",
        "I love you more than you love complaining.",
        "happy anniversary to my favorite weirdo ✿",
      ],
      voicePrompt: "Record a funny, roasty anniversary voice message...",
    },
  },

  birthday: {
    romantic: {
      message: "Wishing the happiest birthday to the one who holds my entire heart! The world became infinitely brighter and more beautiful the day you were born. Today is all about celebrating the incredible person you are.",
      secretLock: {
        question: "What is the sweetest birthday wish you want to come true this year?",
        answer: "Our future together",
        hint: "Think about our biggest shared dream...",
      },
      scratchCoupons: [
        "🎟️ 1x Special Birthday Wish Granted by Me (Anything!)",
        "🎟️ 1x Birthday Pampering Day (Zero Chores & All Royalty)",
        "🎟️ 1x Candlelight Birthday Dinner at Your Dream Spot",
      ],
      certTitle: "Certified Birthday Royalty & Love of My Life",
      terms: [
        "Birthday Royalty Protocol. 100% pampering, compliments, and love today.",
        "First Cake Slice. Guaranteed first and biggest slice of birthday cake.",
        "Wish Multiplier. All birthday wishes made today have double manifesting power.",
        "Celebrated Every Day. We celebrate your presence in my life all year round.",
        "Terms: aging like fine wine, looking more charming every year.",
      ],
      memories: [
        "wishing the happiest birthday to my absolute favorite.",
        "the world became brighter the day you were born.",
        "so grateful I get to celebrate another year of your life.",
        "may all your sweetest dreams come true.",
        "you deserve all the joy, cake, and love in the universe.",
        "happy birthday, my forever love ✿",
      ],
      voicePrompt: "Sing happy birthday or leave a loving birthday voice note...",
    },
    playful: {
      message: "Happy Birthday superstar! You're officially one year older, but let's be honest — maturity is completely overrated. Eat all the cake, make wild wishes, and let's celebrate you today!",
      secretLock: {
        question: "How old are we acting today on your birthday?",
        answer: "Five years old",
        hint: "Cake first, adulting never...",
      },
      scratchCoupons: [
        "🎟️ 1x First & Biggest Slice of Birthday Cake on Demand",
        "🎟️ 1x Free Birthday Drink / Dessert on My Tab",
        "🎟️ 1x You Don't Lift a Single Finger All Day Long",
      ],
      certTitle: "Certified Birthday VIP & Forever Young Legend",
      terms: [
        "Zero Chores Directive. Exempt from all dishes, cleaning, and responsibility.",
        "Sugar Rush Clearance. Permitted to eat cake for breakfast, lunch, and dinner.",
        "Birthday Attention Pass. Center of attention all day, non-negotiable.",
        "Wish Granting. One special wild wish to be carried out by me.",
        "Terms: aging gracefully, staying delightfully silly.",
      ],
      memories: [
        "happy birthday to my favorite chaotic superstar!",
        "another year older, none the wiser.",
        "proof that you're only getting more awesome.",
        "here for the cake and your beautiful smile.",
        "cheers to another great lap around the sun.",
        "happy birthday, legend ✿",
      ],
      voicePrompt: "Record a funny or energetic birthday voice message...",
    },
    nostalgic: {
      message: "Celebrating your birthday always makes me reflect on how precious your life is to everyone around you. Thank you for filling our world with your warmth, laughter, and kindness. Happy Birthday!",
      secretLock: {
        question: "What's the best birthday memory we've shared so far?",
        answer: "Last year's party",
        hint: "That special birthday evening...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-visiting Your Favorite Birthday Memory Spot",
        "🎟️ 1x Custom Birthday Gift Chosen with Love by Me",
        "🎟️ 1x Cozy Memory Night with Favorite Childhood Snacks",
      ],
      certTitle: "Certified Cherished Birthday Star",
      terms: [
        "Life Celebration. Honoring all the wonderful milestones you've conquered.",
        "Endless Support. Cheering for all your upcoming chapters and dreams.",
        "Deep Appreciation. Celebrating your kindness and gentle spirit.",
        "Memory Tribute. Making every year memorable and filled with love.",
        "Terms: blessed with good health, deep joy, and endless peace.",
      ],
      memories: [
        "another year of your wonderful journey in this world.",
        "so proud of everything you've accomplished.",
        "thank you for being such a bright light in my life.",
        "every year with you is a gift.",
        "may this year bring you all the happiness you give others.",
        "happy birthday, my cherished human ✿",
      ],
      voicePrompt: "Record a nostalgic birthday voice memo...",
    },
    wholesome: {
      message: "Happy Birthday to one of the sweetest, most genuine souls in my life! I hope this year brings you gentle mornings, peaceful evenings, exciting dreams, and all the love your heart can hold.",
      secretLock: {
        question: "What is your biggest heartfelt wish for this new chapter?",
        answer: "Peace and happiness",
        hint: "The most beautiful wish of all...",
      },
      scratchCoupons: [
        "🎟️ 1x Complete Day of Peace, Self-Care & Pampering",
        "🎟️ 1x Hand-Baked Birthday Treats Made Just for You",
        "🎟️ 1x Birthday Warm Hugs & Affirmation Session",
      ],
      certTitle: "Certified Pure Sunshine Birthday Soul",
      terms: [
        "Peace & Comfort Protocol. Surrounded by love, kindness, and warmth today.",
        "Sweet Blessings. Manifesting health, joy, and wonderful surprises for you.",
        "Unconditional Care. Always having a circle of love around you.",
        "Birthday Gentle Hugs. Unlimited comforting embraces.",
        "Terms: wrapped in love and endless blessings.",
      ],
      memories: [
        "the sweetest birthday star in the universe.",
        "may your year be as kind as your heart.",
        "blessed to celebrate another year of you.",
        "pure joy, love, and sunshine for your new chapter.",
        "wishing you the most beautiful birthday ever.",
        "happy birthday with all my heart ✿",
      ],
      voicePrompt: "Record a sweet, heartwarming birthday voice note...",
    },
    funny: {
      message: "Happy Birthday! Science says that people who have more birthdays live longer. So congratulations on your groundbreaking scientific achievement! Now give me some cake.",
      secretLock: {
        question: "Who is the favorite person wishing you happy birthday?",
        answer: "Me of course",
        hint: "The one who made this website...",
      },
      scratchCoupons: [
        "🎟️ 1x You Don't Have to Share Any Birthday Food",
        "🎟️ 1x Free Pass to Complain About Your Back/Knees",
        "🎟️ 1x Birthday Drinks & Tacos on My Tab",
      ],
      certTitle: "Certified Birthday Legend Surviving Another Year",
      terms: [
        "Aging Exception. Still looking remarkably youthful and charming.",
        "Cake Supremacy. Absolute authority over the cake cutting.",
        "Birthday Immunity. Free to act completely childish all day.",
        "Birthday Hype. Everyone must clap when you enter the room.",
        "Terms: certified for another 365 days of glory.",
      ],
      memories: [
        "happy birthday to my favorite old person.",
        "you're not old, you're just vintage.",
        "another year of being undeniably fabulous.",
        "can't wait to eat your birthday cake.",
        "so glad you were born to put up with me.",
        "happy birthday, rockstar ✿",
      ],
      voicePrompt: "Record a funny, roasty birthday voice note...",
    },
  },

  custom: {
    romantic: {
      message: "I wanted to take a moment and remind you how much you mean to me. Life is infinitely richer, warmer, and sweeter with you in it. I built this little corner of the internet just for you.",
      secretLock: {
        question: "Our special secret keyword?",
        answer: "Love",
        hint: "The feeling we share...",
      },
      scratchCoupons: [
        "🎟️ 1x Special Wish Granted by Me",
        "🎟️ 1x Day of Complete Relaxation & Treat",
        "🎟️ 1x Unlimited Big Hugs Voucher",
      ],
      certTitle: "Certified Extraordinary Human",
      terms: [
        "Pure Sunshine Award. Bringing happiness and good vibes wherever you go.",
        "Always Appreciated. For all the little and big things that make you uniquely you.",
        "Smiles Guaranteed. Required to smile while reading this special surprise.",
        "Priority VIP Status. Forever holds a special place in my thoughts and heart.",
        "Terms: valid forever, non-negotiable and guaranteed.",
      ],
      memories: [
        "thank you for being such a wonderful part of my life.",
        "every moment shared with you is memorable.",
        "never forget how truly incredible you are.",
        "here is to all our past memories and many more to come.",
        "you make every ordinary day feel extraordinary.",
        "always cheering for you ✿",
      ],
      voicePrompt: "Record a custom audio message...",
    },
    playful: {
      message: "Surprise! You've been selected for a special VIP digital tribute because you're awesome and you deserve nice things. Enjoy your personalized corner of the internet!",
      secretLock: {
        question: "What's our favorite fun memory together?",
        answer: "That funny day",
        hint: "When we laughed until we couldn't breathe...",
      },
      scratchCoupons: [
        "🎟️ 1x Free Treat / Coffee on My Tab",
        "🎟️ 1x I Do 1 Chore for You No Questions Asked",
        "🎟️ 1x VIP Pass to Hang Out & Relax All Day",
      ],
      certTitle: "Certified VIP Legend of Awesomeness",
      terms: [
        "VIP Status. Exempt from boredom and bad vibes.",
        "Fun Enforcement. Mandatory fun and good music.",
        "Snack Entitlement. Guaranteed access to treats.",
        "Champion of Good Vibes. Spreading smiles everywhere.",
        "Terms: valid for life.",
      ],
      memories: [
        "a special surprise for an awesome person.",
        "proof of peak fun moments.",
        "you make everything more exciting.",
        "cheers to more good times ahead.",
        "stay amazing and keep shining.",
        "with all the best vibes ✿",
      ],
      voicePrompt: "Record a playful custom voice message...",
    },
    nostalgic: {
      message: "Taking a moment to pause and celebrate our shared journey. Life moves so fast, but the memories we've created will always stay close to my heart. Here's to us and everything we've shared.",
      secretLock: {
        question: "Where did our journey first begin?",
        answer: "The beginning",
        hint: "Think back to the start...",
      },
      scratchCoupons: [
        "🎟️ 1x Re-visiting Our Favorite Memory Together",
        "🎟️ 1x Long Catch-Up Session Over Hot Drinks",
        "🎟️ 1x Memory Photo Scrapbook Night",
      ],
      certTitle: "Certified Cherished Journey & Companion",
      terms: [
        "Cherished Moments. Honoring every memory along the way.",
        "Timeless Connection. A bond that stays strong through time.",
        "Gratitude Pact. Thankful for every step of the journey.",
        "Endless Support. Standing by each other always.",
        "Terms: timeless and true.",
      ],
      memories: [
        "where our story first started.",
        "every milestone conquered together.",
        "the quiet moments that meant the most.",
        "thank you for being there through it all.",
        "memories that will last forever.",
        "warmest wishes, always ✿",
      ],
      voicePrompt: "Record a nostalgic custom voice message...",
    },
    wholesome: {
      message: "Sending you a little dose of warmth, gratitude, and happiness. You bring so much good into the world, and I hope this page serves as a sweet reminder of how much you are appreciated.",
      secretLock: {
        question: "What's our favorite peaceful activity?",
        answer: "Quiet time",
        hint: "Relaxing and enjoying the moment...",
      },
      scratchCoupons: [
        "🎟️ 1x Self-Care & Complete Relaxation Pass",
        "🎟️ 1x Warm Beverage & Gentle Chat Session",
        "🎟️ 1x Unlimited Warm Hugs & Encouragement",
      ],
      certTitle: "Certified Pure Heart & Joy Dispenser",
      terms: [
        "Gentle Care. May your days be soft, kind, and peaceful.",
        "Constant Warmth. A gentle reminder that you are loved.",
        "Safe Space. Always having encouragement when needed.",
        "Daily Smiles. Required to smile and take it easy.",
        "Terms: blessed with pure joy.",
      ],
      memories: [
        "sending you warmth and comfort.",
        "thank you for being your wonderful self.",
        "you make the world a gentler place.",
        "wishing you all the peace in the world.",
        "always in my thoughts and heart.",
        "with gentle love ✿",
      ],
      voicePrompt: "Record a warm custom voice message...",
    },
    funny: {
      message: "Breaking News: You are officially recognized as a certified legend. I spent actual minutes building this website for you, so you better appreciate it!",
      secretLock: {
        question: "Who is your coolest friend / partner?",
        answer: "Me",
        hint: "The genius behind this page...",
      },
      scratchCoupons: [
        "🎟️ 1x Free Pass to Boast About Having a Website",
        "🎟️ 1x Free Food on My Tab",
        "🎟️ 1x 24 Hours of Pure VIP Bragging Rights",
      ],
      certTitle: "Certified Supreme Legend of the Century",
      terms: [
        "Supreme Swag. Certified to possess unmatched humor and coolness.",
        "Free Food Entitlement. May redeem snacks from me on demand.",
        "Bragging Rights. Legally allowed to show this site to everyone.",
        "VIP Treatment. Red carpet service at all times.",
        "Terms: certified 100% legendary.",
      ],
      memories: [
        "look at this absolute legend.",
        "a rare sighting of peak excellence.",
        "proof that you are one of a kind.",
        "never change your hilarious self.",
        "cheers to you, rockstar.",
        "stay awesome, legend ✿",
      ],
      voicePrompt: "Record a funny, roasty custom voice note...",
    },
  },
};

/* Curated Wholesome Viral Meme Library */
export const VIRAL_MEME_LIBRARY: MemeItem[] = [
  { id: 1, title: "I'm so Youholic", category: 'funny', src: '/library/viral_1.jpg', caption: 'Cute tongue blep' },
  { id: 2, title: 'i lve u babyyy muwaah', category: 'romantic', src: '/library/viral_2.jpg', caption: 'Sweet baby kissies' },
  { id: 3, title: 'Arrested in your love', category: 'funny', src: '/library/viral_3.jpg', caption: 'Kitty in tiny handcuffs' },
  { id: 4, title: 'Floating Hearts Shiba', category: 'romantic', src: '/library/viral_4.jpg', caption: 'Blissful Shiba surrounded by hearts' },
  { id: 5, title: 'Cheese Smile Dog + Flower', category: 'cute', src: '/library/viral_5.jpg', caption: 'Big cheeky grin holding yellow flower' },
  { id: 6, title: 'my pretty boyy / girl', category: 'romantic', src: '/library/viral_6.jpg', caption: 'Fluffy kitten staring up lovingly' },
  { id: 7, title: 'You Are My Whole World', category: 'romantic', src: '/library/viral_7.jpg', caption: 'Kitten with bright heart halo' },
  { id: 8, title: 'I Am Baby, Give Me Love', category: 'cute', src: '/library/viral_8.jpg', caption: 'Warm kitten burrito in soft blanket' },
  { id: 9, title: 'Flower For My Favorite Person', category: 'romantic', src: '/library/viral_9.jpg', caption: 'Golden puppy with fresh flower' },
  { id: 10, title: 'Sweetest Strawberry Treat', category: 'cute', src: '/library/viral_10.jpg', caption: 'Cute tiny hamster nibbling strawberry' },
  { id: 11, title: 'Warm Bunny Snuggles', category: 'cute', src: '/library/viral_11.jpg', caption: 'Fluffy rabbit resting in flowers' },
  { id: 12, title: 'Paws Around My Heart', category: 'cute', src: '/library/viral_12.jpg', caption: 'Tiny kitten clutching its little paws' },
  { id: 13, title: 'Caught Winking at You', category: 'funny', src: '/library/viral_13.jpg', caption: 'Cheeky Corgi dog winking playfully' },
  { id: 14, title: 'Dreaming Only of You', category: 'romantic', src: '/library/viral_14.jpg', caption: 'Sleepy peaceful baby kitten' },
  { id: 15, title: 'Head Tilted For You', category: 'cute', src: '/library/viral_15.jpg', caption: 'Golden retriever pup head tilt' },
  { id: 16, title: 'Holding Hands Forever', category: 'romantic', src: '/library/viral_16.jpg', caption: 'Two sea otters holding paws together' },
  { id: 17, title: 'The Brightest Smile', category: 'cute', src: '/library/viral_17.jpg', caption: 'Fluffy white smiling Samoyed dog' },
  { id: 18, title: 'Hypnotized By You', category: 'funny', src: '/library/viral_18.jpg', caption: 'Saucer eyes kitten looking up' },
  { id: 19, title: 'Silly Blep Just For You', category: 'funny', src: '/library/viral_19.jpg', caption: 'Goofy puppy sticking tongue out' },
  { id: 20, title: 'Curious Red Panda Paws', category: 'cute', src: '/library/viral_20.jpg', caption: 'Fluffy red panda reaching up curiously' },
  { id: 21, title: 'Heart-Shaped Boop', category: 'romantic', src: '/library/viral_21.jpg', caption: 'Cat with cute heart-shaped nose' },
  { id: 22, title: 'Cozy In Your Warmth', category: 'cute', src: '/library/viral_22.jpg', caption: 'Cute puppy tucked in knit beanie' },
  { id: 23, title: 'Sunny Grass Zoomies', category: 'cute', src: '/library/viral_23.jpg', caption: 'Golden puppy tumbling in the lawn' },
  { id: 24, title: 'Looking Up At My World', category: 'romantic', src: '/library/viral_24.jpg', caption: 'Frenchie puppy gazing with affection' },
  { id: 25, title: 'Angel Cloud of Love', category: 'romantic', src: '/library/viral_25.jpg', caption: 'Pure white kitten with bright blue eyes' },
  { id: 26, title: 'I Miss You Warm Hug (GIF)', category: 'romantic', src: '/assets/missyou.gif', caption: 'Sweet missing you animation' },
  { id: 27, title: 'Missing You Across Miles (GIF)', category: 'romantic', src: '/assets/missyou.gif', caption: 'Long distance love animation' },
  { id: 28, title: 'True Love Hug (GIF)', category: 'romantic', src: '/assets/love.gif', caption: 'Heartwarming romantic hug' },
  { id: 29, title: 'Boka Hugs (GIF)', category: 'cute', src: '/assets/boka.gif', caption: 'Cute animated boka bear' },
  { id: 30, title: 'Besties Forever (GIF)', category: 'funny', src: '/assets/friend.gif', caption: 'High five best friends' },
  { id: 31, title: 'Happy Cat Play (GIF)', category: 'cute', src: '/assets/cat.gif', caption: 'Adorable animated kitty' },
  { id: 32, title: 'Birthday Confetti Dance (GIF)', category: 'funny', src: '/assets/birthday.gif', caption: 'Birthday celebration dance' },
  { id: 33, title: 'Happy Birthday Party (GIF)', category: 'funny', src: '/assets/birthday.gif', caption: 'Birthday party celebration' },
  { id: 34, title: 'Happy Anniversary Love (GIF)', category: 'romantic', src: '/assets/anniversary.gif', caption: 'Forever together animation' },
];

export const WITNESS_NAME_MAP: Record<string, string> = {
  cat: 'the cat (official witness)',
  boka: 'boka (official cute witness)',
  friend: 'best friend (partner in crime)',
  dog: 'good doggo (official good boy)',
  moon: 'the moon (connecting our hearts)',
  cupid: 'cupid himself (official witness)',
  custom: 'our best friend (witness)',
};

/* Base Presets */
export const EVENT_PRESETS: Record<EventType, EventPreset> = {
  boyfriend: {
    name: "Boyfriend's Day",
    handTag: "happy boyfriend's day",
    headline: "Make him a little corner of the internet",
    senderLabel: "Your name",
    receiverLabel: "His name",
    senderPlaceholder: "Priya",
    receiverPlaceholder: "Rahul",
    defaultVibe: "romantic",
    defaultMessage: VIBE_CONTENT_MAP.boyfriend.romantic.message,
    theme: VIBE_THEMES.wholesome,
    envelope: {
      h2: "Hey You!",
      p1: "I made a little something<br>just for you...",
      p2: "happy boyfriend's day ✿",
      stamp: "HAPPY BOYFRIEND'S DAY",
      heart: "♥",
    },
    viewerEyebrow: "HAPPY BOYFRIEND'S DAY",
    certificate: {
      badge: "CERTIFICATE OF BOYFRIENDSHIP",
      title: VIBE_CONTENT_MAP.boyfriend.romantic.certTitle,
      sub: "is hereby the one and only official boyfriend, with these lifelong duties:",
      witness: "the cat",
      terms: VIBE_CONTENT_MAP.boyfriend.romantic.terms,
    },
    memories: VIBE_CONTENT_MAP.boyfriend.romantic.memories,
    secretLock: VIBE_CONTENT_MAP.boyfriend.romantic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.boyfriend.romantic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.boyfriend.romantic.voicePrompt,
    signoff: "always yours",
  },

  girlfriend: {
    name: "Girlfriend's Day",
    handTag: "happy girlfriend's day ✿",
    headline: "Make her a little corner of the internet",
    senderLabel: "Your name",
    receiverLabel: "Her name",
    senderPlaceholder: "Aarav",
    receiverPlaceholder: "Ananya",
    defaultVibe: "romantic",
    defaultMessage: VIBE_CONTENT_MAP.girlfriend.romantic.message,
    theme: VIBE_THEMES.romantic,
    envelope: {
      h2: "Hey Gorgeous!",
      p1: "A little surprise made with love<br>just for you...",
      p2: "happy girlfriend's day ✿",
      stamp: "HAPPY GIRLFRIEND'S DAY",
      heart: "💖",
    },
    viewerEyebrow: "HAPPY GIRLFRIEND'S DAY",
    certificate: {
      badge: "CERTIFICATE OF PRINCESS TREATMENT",
      title: VIBE_CONTENT_MAP.girlfriend.romantic.certTitle,
      sub: "is officially certified as the Queen of My Heart, entitled to lifelong royal rights:",
      witness: "boka",
      terms: VIBE_CONTENT_MAP.girlfriend.romantic.terms,
    },
    memories: VIBE_CONTENT_MAP.girlfriend.romantic.memories,
    secretLock: VIBE_CONTENT_MAP.girlfriend.romantic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.girlfriend.romantic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.girlfriend.romantic.voicePrompt,
    signoff: "forever yours",
  },

  bestfriend: {
    name: "Best Friend / Friendship Day",
    handTag: "to my partner in crime 👯‍♀️",
    headline: "A digital shrine for our beautiful chaos",
    senderLabel: "Your name",
    receiverLabel: "Bestie's name",
    senderPlaceholder: "Sam",
    receiverPlaceholder: "Alex",
    defaultVibe: "playful",
    defaultMessage: VIBE_CONTENT_MAP.bestfriend.playful.message,
    theme: VIBE_THEMES.playful,
    envelope: {
      h2: "Yo Bestie!",
      p1: "I made a little digital shrine<br>for our mutual chaos...",
      p2: "happy best friend day ✿",
      stamp: "CHAOS PARTNER FOR LIFE",
      heart: "⭐",
    },
    viewerEyebrow: "HAPPY BEST FRIEND DAY",
    certificate: {
      badge: "CERTIFICATE OF PARTNERSHIP IN CHAOS",
      title: VIBE_CONTENT_MAP.bestfriend.playful.certTitle,
      sub: "is officially recognized as the Chief Partner in Crime with these mutual pacts:",
      witness: "best friend",
      terms: VIBE_CONTENT_MAP.bestfriend.playful.terms,
    },
    memories: VIBE_CONTENT_MAP.bestfriend.playful.memories,
    secretLock: VIBE_CONTENT_MAP.bestfriend.playful.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.bestfriend.playful.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.bestfriend.playful.voicePrompt,
    signoff: "your favorite human",
  },

  valentines: {
    name: "Valentine's Day",
    handTag: "to my forever valentine ♥",
    headline: "A love letter hidden in the internet",
    senderLabel: "Your name",
    receiverLabel: "Valentine's name",
    senderPlaceholder: "Dev",
    receiverPlaceholder: "Riya",
    defaultVibe: "romantic",
    defaultMessage: VIBE_CONTENT_MAP.valentines.romantic.message,
    theme: VIBE_THEMES.romantic,
    envelope: {
      h2: "My Valentine ♥",
      p1: "A secret love letter hidden<br>in the internet for you...",
      p2: "happy valentine's day ✿",
      stamp: "VALENTINE FOR LIFE",
      heart: "💖",
    },
    viewerEyebrow: "HAPPY VALENTINE'S DAY",
    certificate: {
      badge: "CERTIFICATE OF ETERNAL LOVE",
      title: VIBE_CONTENT_MAP.valentines.romantic.certTitle,
      sub: "is hereby granted supreme soulmate rights & romantic responsibilities:",
      witness: "cupid himself",
      terms: VIBE_CONTENT_MAP.valentines.romantic.terms,
    },
    memories: VIBE_CONTENT_MAP.valentines.romantic.memories,
    secretLock: VIBE_CONTENT_MAP.valentines.romantic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.valentines.romantic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.valentines.romantic.voicePrompt,
    signoff: "with all my heart",
  },

  missyou: {
    name: "I Miss You / Long Distance",
    handTag: "miles apart, close at heart ✈️",
    headline: "Sending a warm hug through the screen",
    senderLabel: "Your name",
    receiverLabel: "Their name",
    senderPlaceholder: "Maya",
    receiverPlaceholder: "Arjun",
    defaultVibe: "nostalgic",
    defaultMessage: VIBE_CONTENT_MAP.missyou.nostalgic.message,
    theme: VIBE_THEMES.nostalgic,
    envelope: {
      h2: "Hey You...",
      p1: "Sending a warm digital hug<br>across the miles...",
      p2: "missing you so much ✿",
      stamp: "DISTANCE MEANS NOTHING",
      heart: "✨",
    },
    viewerEyebrow: "THINKING OF YOU ALWAYS",
    certificate: {
      badge: "CERTIFICATE OF MILES & MEMORIES",
      title: VIBE_CONTENT_MAP.missyou.nostalgic.certTitle,
      sub: "is officially certified as deeply missed with these long-distance treaties:",
      witness: "the moon between us",
      terms: VIBE_CONTENT_MAP.missyou.nostalgic.terms,
    },
    memories: VIBE_CONTENT_MAP.missyou.nostalgic.memories,
    secretLock: VIBE_CONTENT_MAP.missyou.nostalgic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.missyou.nostalgic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.missyou.nostalgic.voicePrompt,
    signoff: "missing you always",
  },

  anniversary: {
    name: "Anniversary",
    handTag: "celebrating our love milestone 💍",
    headline: "Another year of loving you more",
    senderLabel: "Your name",
    receiverLabel: "Partner's name",
    senderPlaceholder: "Kavya",
    receiverPlaceholder: "Rohan",
    defaultVibe: "romantic",
    defaultMessage: VIBE_CONTENT_MAP.anniversary.romantic.message,
    theme: VIBE_THEMES.wholesome,
    envelope: {
      h2: "Happy Anniversary!",
      p1: "Another beautiful chapter with you...<br>open our story so far...",
      p2: "happy anniversary ✿",
      stamp: "CELEBRATING US",
      heart: "💍",
    },
    viewerEyebrow: "HAPPY ANNIVERSARY",
    certificate: {
      badge: "CERTIFICATE OF EVERLASTING LOVE",
      title: VIBE_CONTENT_MAP.anniversary.romantic.certTitle,
      sub: "is officially celebrated for another year of partnership, laughter, and love:",
      witness: "destiny itself",
      terms: VIBE_CONTENT_MAP.anniversary.romantic.terms,
    },
    memories: VIBE_CONTENT_MAP.anniversary.romantic.memories,
    secretLock: VIBE_CONTENT_MAP.anniversary.romantic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.anniversary.romantic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.anniversary.romantic.voicePrompt,
    signoff: "with endless love",
  },

  birthday: {
    name: "Birthday",
    handTag: "happy birthday superstar 🎂",
    headline: "Make their birthday unforgettable",
    senderLabel: "Your name",
    receiverLabel: "Birthday star's name",
    senderPlaceholder: "Sneha",
    receiverPlaceholder: "Karan",
    defaultVibe: "playful",
    defaultMessage: VIBE_CONTENT_MAP.birthday.playful.message,
    theme: {
      '--bg': '#fffbf0',
      '--ink': '#3e2723',
      '--teal': '#e65100',
      '--teal-d': '#bf360c',
      '--mint': '#ffe0b2',
      '--peach': '#ff7043',
      '--gold': '#ffa000',
      '--line': '#fff3e0',
    },
    envelope: {
      h2: "Make a Wish! 🎂",
      p1: "Someone made you a little<br>birthday corner on the internet...",
      p2: "happy birthday superstar ✿",
      stamp: "BIRTHDAY VIP PASS",
      heart: "🎂",
    },
    viewerEyebrow: "HAPPY BIRTHDAY",
    certificate: {
      badge: "CERTIFICATE OF BIRTHDAY ROYALTY",
      title: VIBE_CONTENT_MAP.birthday.playful.certTitle,
      sub: "is hereby granted supreme birthday royal honors and privileges:",
      witness: "the birthday cake fairy",
      terms: VIBE_CONTENT_MAP.birthday.playful.terms,
    },
    memories: VIBE_CONTENT_MAP.birthday.playful.memories,
    secretLock: VIBE_CONTENT_MAP.birthday.playful.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.birthday.playful.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.birthday.playful.voicePrompt,
    signoff: "cheers to you",
  },

  custom: {
    name: "Custom Event",
    handTag: "a little surprise for you ✨",
    headline: "Make someone special a little corner of the internet",
    senderLabel: "Your name",
    receiverLabel: "Their name",
    senderPlaceholder: "Your Name",
    receiverPlaceholder: "Their Name",
    defaultVibe: "romantic",
    defaultMessage: VIBE_CONTENT_MAP.custom.romantic.message,
    theme: VIBE_THEMES.wholesome,
    envelope: {
      h2: "Surprise!",
      p1: "A little corner of the internet<br>made just for you...",
      p2: "with love ✿",
      stamp: "SPECIAL EDITION",
      heart: "✨",
    },
    viewerEyebrow: "JUST FOR YOU",
    certificate: {
      badge: "CERTIFICATE OF AWESOMENESS",
      title: VIBE_CONTENT_MAP.custom.romantic.certTitle,
      sub: "is officially recognized for being exceptional with these honors:",
      witness: "the whole universe",
      terms: VIBE_CONTENT_MAP.custom.romantic.terms,
    },
    memories: VIBE_CONTENT_MAP.custom.romantic.memories,
    secretLock: VIBE_CONTENT_MAP.custom.romantic.secretLock,
    scratchCoupons: VIBE_CONTENT_MAP.custom.romantic.scratchCoupons,
    voicePrompt: VIBE_CONTENT_MAP.custom.romantic.voicePrompt,
    signoff: "warmest wishes",
  },
};
